CREATE TABLE tb_users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    phone      VARCHAR(255)                            NOT NULL,
    birth_date DATE                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    role       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_users PRIMARY KEY (id)
);

CREATE TABLE tb_specialties
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_specialties PRIMARY KEY (id)
);

CREATE TABLE tb_assistants
(
    id                  BIGINT       NOT NULL,
    registration_number VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tb_assistants PRIMARY KEY (id)
);

CREATE TABLE tb_doctors
(
    id  BIGINT       NOT NULL,
    crm VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tb_doctors PRIMARY KEY (id)
);

CREATE TABLE tb_patients
(
    id  BIGINT       NOT NULL,
    cpf VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tb_patients PRIMARY KEY (id)
);

CREATE TABLE tb_doctor_schedules
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    doctor_id   BIGINT                                  NOT NULL,
    day_of_week VARCHAR(255)                            NOT NULL,
    start_time  TIME WITHOUT TIME ZONE                  NOT NULL,
    end_time    TIME WITHOUT TIME ZONE                  NOT NULL,
    CONSTRAINT pk_tb_doctor_schedules PRIMARY KEY (id)
);

CREATE TABLE tb_doctor_specialty
(
    doctor_id    BIGINT NOT NULL,
    specialty_id BIGINT NOT NULL,
    CONSTRAINT pk_tb_doctor_specialty PRIMARY KEY (doctor_id, specialty_id)
);

CREATE TABLE tb_appointments
(
    id                 UUID         NOT NULL,
    status             VARCHAR(255) NOT NULL,
    date_time          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    assistant_id       BIGINT,
    doctor_schedule_id BIGINT       NOT NULL,
    patient_id         BIGINT,
    CONSTRAINT pk_tb_appointments PRIMARY KEY (id)
);

ALTER TABLE tb_assistants
    ADD CONSTRAINT uc_tb_assistants_registration_number UNIQUE (registration_number);

ALTER TABLE tb_doctors
    ADD CONSTRAINT uc_tb_doctors_crm UNIQUE (crm);

ALTER TABLE tb_patients
    ADD CONSTRAINT uc_tb_patients_cpf UNIQUE (cpf);

ALTER TABLE tb_specialties
    ADD CONSTRAINT uc_tb_specialties_name UNIQUE (name);

ALTER TABLE tb_users
    ADD CONSTRAINT uc_tb_users_email UNIQUE (email);

ALTER TABLE tb_users
    ADD CONSTRAINT uc_tb_users_phone UNIQUE (phone);

ALTER TABLE tb_assistants
    ADD CONSTRAINT FK_TB_ASSISTANTS_ON_ID FOREIGN KEY (id) REFERENCES tb_users (id);

ALTER TABLE tb_doctors
    ADD CONSTRAINT FK_TB_DOCTORS_ON_ID FOREIGN KEY (id) REFERENCES tb_users (id);

ALTER TABLE tb_patients
    ADD CONSTRAINT FK_TB_PATIENTS_ON_ID FOREIGN KEY (id) REFERENCES tb_users (id);

ALTER TABLE tb_doctor_schedules
    ADD CONSTRAINT FK_TB_DOCTOR_SCHEDULES_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES tb_doctors (id);

ALTER TABLE tb_doctor_specialty
    ADD CONSTRAINT fk_tbdocspe_on_doctor FOREIGN KEY (doctor_id) REFERENCES tb_doctors (id);

ALTER TABLE tb_doctor_specialty
    ADD CONSTRAINT fk_tbdocspe_on_specialty FOREIGN KEY (specialty_id) REFERENCES tb_specialties (id);

ALTER TABLE tb_appointments
    ADD CONSTRAINT FK_TB_APPOINTMENTS_ON_ASSISTANT FOREIGN KEY (assistant_id) REFERENCES tb_assistants (id);

ALTER TABLE tb_appointments
    ADD CONSTRAINT FK_TB_APPOINTMENTS_ON_DOCTORSCHEDULE FOREIGN KEY (doctor_schedule_id) REFERENCES tb_doctor_schedules (id);

ALTER TABLE tb_appointments
    ADD CONSTRAINT FK_TB_APPOINTMENTS_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES tb_patients (id);