server:
  port: 8082

spring:
  aws:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket-name: ${AWS_BUCKET_NAME}
      region: ${AWS_REGION}

  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:mem:testdb;
    username: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES}
    queues:
      appointment:
        name: appointment.generate-pdf.queue

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html