server:
  port: 8080

api:
  security:
    token:
      secret: my-secret-key

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/consultas_medicas_db}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES}
    queues:
      appointment:
        name: appointment.generate-pdf.queue

  web:
    resources:
      add-mappings: false