spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_agendamento_consultas_db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  web:
    resources:
      add-mappings: false

api:
  security:
    token:
      secret: my-secret-key